//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YazOkuluDersKaydi.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbYazOkuluDersKaydıEntities2 : DbContext
    {
        public DbYazOkuluDersKaydıEntities2()
            : base("name=DbYazOkuluDersKaydıEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblDersler> TblDersler { get; set; }
        public virtual DbSet<TblOgrenci> TblOgrenci { get; set; }
        public virtual DbSet<TblOgrenciDers> TblOgrenciDers { get; set; }
        public virtual DbSet<VwOgrenciDers> VwOgrenciDers { get; set; }
    }
}
