//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YazOkuluDersKaydi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblOgrenciDers
    {
        public int Id { get; set; }
        public int OgrenciId { get; set; }
        public int DersId { get; set; }
        public string DersAdi { get; set; }
        public string AlanAdi { get; set; }
        public Nullable<int> Kontenjan { get; set; }
        public Nullable<double> DersUcreti { get; set; }
        public Nullable<System.Guid> DersGuid { get; set; }
        public Nullable<bool> Aktif { get; set; }
        public Nullable<bool> Silik { get; set; }
    }
}
