//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YazOkuluDersKaydi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwOgrenciDers
    {
        public int OgrenciId { get; set; }
        public Nullable<long> OgrenciNumarasi { get; set; }
        public string OgrenciAdi { get; set; }
        public string OgrenciSoyadi { get; set; }
        public Nullable<System.Guid> OgrenciGuid { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public Nullable<bool> Aktif { get; set; }
        public Nullable<bool> Silik { get; set; }
        public string DersAdi { get; set; }
        public Nullable<int> Kontenjan { get; set; }
        public Nullable<double> DersUcreti { get; set; }
        public Nullable<System.Guid> DersGuid { get; set; }
        public int OgretmenAdi { get; set; }
        public string DersAdiBirlesik { get; set; }
        public string AlanAdi { get; set; }
    }
}
